### ISSUE TITLE
fix robot tests

### ISSUE THREAD

**Issue by gasolin** [gasolin/webbybot#31]
there's some skipped tests in robot_test related to middleware and listener

**Comment by gasolin** [comment]
@raylin do you have time to check that?

**Comment by raylin** [comment]
ok l'll see what I can do

**Comment by raylin** [comment]
not yet finished patch... 
https://github.com/raylin/webbybot/commit/83c501b867c6c5d0f0d1f3bcec565375a28542eb

still 2 fails left, need to look into robot and listener

**Comment by gasolin** [comment]
fixed in  2ccd152
